<a href="https://colab.research.google.com/github/ssvadla/Bridge_Project/blob/main/Bridge_Project_Data_Analysis_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install geopandas
import geopandas as gpd
import os
import pandas as pd
import numpy as np 

from google.colab import drive
drive.mount('/content/drive')

shape_files = []

data_frames_list = []
data_frames_shape_list = []
data_frames_rows_list = []
data_frames_cols_list = []
state_name_dict_cols = { }
root_path = '/content/drive/My Drive/Bridge_Project/Bridge_Data/'

content_list = os.listdir(root_path)
print("content_list = ",len(content_list))



for i in content_list:
  split = i.split(".")
  if split[1] == 'shp' and len(split) == 2:
    shape_files.append(i)

shape_files.sort()
print("shape_files = ",len(shape_files))

for i in shape_files:

  shp_file_path = root_path + i
  print(shp_file_path)
  df = gpd.read_file(shp_file_path)  
  data_frames_list.append(df)
  state_name_dict_cols[i] = [ df.shape[0], df.shape[1] ] #write to file
  data_frames_shape_list.append(df.shape) #file
  data_frames_rows_list.append(df.shape[0]) # file
  data_frames_cols_list.append(df.shape[1]) #file

if np.unique(data_frames_cols_list) != 138:
  print("columns are not the same for all states")
  check_cols_same = 'columns are not the same for all states' 
else :
  check_cols_same = 'olumns are same for all states'# file

if sum(data_frames_rows_list) != 612388:
  check_tot_rows = "Total number of rows does not match"
  print("Total number of rows does not match") 
else:
  check_tot_rows = "Total number of rows match to 612388" #file



     |████████████████████████████████| 994 kB 4.7 MB/s 
     |████████████████████████████████| 6.3 MB 20.5 MB/s 
     |████████████████████████████████| 15.4 MB 37 kB/s 
Mounted at /content/drive
content_list =  440
shape_files =  49
/content/drive/My Drive/Bridge_Project/Bridge_Data/Alabama.shp
/content/drive/My Drive/Bridge_Project/Bridge_Data/Arizona.shp
/content/drive/My Drive/Bridge_Project/Bridge_Data/Arkansas.shp
/content/drive/My Drive/Bridge_Project/Bridge_Data/California.shp
/content/drive/My Drive/Bridge_Project/Bridge_Data/Colorado.shp
/content/drive/My Drive/Bridge_Project/Bridge_Data/Connecticut.shp
/content/drive/My Drive/Bridge_Project/Bridge_Data/Delaware.shp
/content/drive/My Drive/Bridge_Project/Bridge_Data/District_of_Columbia.shp
/content/drive/My Drive/Bridge_Project/Bridge_Data/Florida.shp
/content/drive/My Drive/Bridge_Project/Bridge_Data/Georgia.shp
/content/drive/My Drive/Bridge_Project/Bridge_Data/Idaho.shp
/content/drive/My Drive/Bridge_Project/Bridge_Data

In [ ]:
data_frames_rows_list

In [2]:
sum(data_frames_rows_list)

612388

In [3]:
22962 + 16117 + 8424

47503

In [4]:
import numpy as np
np.unique(data_frames_cols_list) 


array([138])

In [6]:
# city = 'Michigan.shp'
# path = root_path+city
# mach_df = gpd.read_file(path)


In [7]:
# print(mach_df.columns)

In [8]:
# city = 'New_Mexico.shp'
# path = root_path+city
# mach_df = gpd.read_file(path)


In [9]:
# mach_df.shape

In [10]:
# for i in range(len(data_frames_cols_list)):
#   if data_frames_cols_list[i] == 139:
#     print(i)
#     print("hello")

In [11]:
#all_cols = ConterminousUS.columns

In [5]:
Initial_Col_Name_list = ['YEAR_B', 'STRUCTUR_4', 'DECK_W', 'DEGRE', 'MAIN_', 'MAX_S', 'STRUCTUR_2', 'DECK_S', 'SURFA', 'DECK_P', 'ADT_0', 'PERCE', 'YEAR_R', 'Shape *', 'STATE', 'STRUCTURE_', 'lattd', 'lngtd', 'DECK_C', 'SUPER', 'SUBST', 'Frequency_', 'Max_Quake', 'DT00', 'DX32', 'DX70', 'DX90', 'AWND', 'WSF5', 'PRECIPITAT', 'TEMP_MAX', 'TEMP_MEAN', 'TEMP_MIN', 'FREQUENCY_','MAX_QUAKE','DATE_'] #file

In [6]:
len(Initial_Col_Name_list)

36

In [14]:
# len(Final_Column_Name)

In [15]:
# attributes = []
# for att in all_cols:
#   if att not in Initial_Col_Name_list:
#     del ConterminousUS[att]
#     #print("not same")
#   else:
#     #print("same")
#     attributes.append(att)

# print(ConterminousUS.shape)
# #attributes to the file

In [16]:
# missing_attr = []
# for i in Initial_Col_Name_list:
#   if i not in all_cols:
#     print(i)
#     missing_attr.append(i)

In [17]:
# for i in all_cols:
#   if i == 'Max_Quake':
#     print("der")

In [18]:
# all_cols.sort_values

In [7]:
Final_Column_Name = ['Year_Built', 'Deck_Length', 'Deck_Width', 'Skew', 'Number_Spans', 'Length_Max_Span', 'Main_Design_Type', 'Deck_Design_Type', 'Wearing_Surface', 'Deck_Protection', 'ADT', 'ADTT', 'Reconstructed_Year', 'Shape *', 'State_Code', 'Structure_Number', 'Latitude', 'Longitude', 'Deck_Condition', 'Superstructure_Condition', 'Substructure_Condition', 'Freq_Shake_GT4', 'Max_Shake', 'Days_MinLT_0F', 'Days_MinLT_32F', 'Days_MaxGT_70F', 'Days_MaxGT_90F', 'Avg_Wind_Speed', 'Peak_Wind_Speed', 'Precipitation', 'Temp_Max', 'Temp_Mean', 'Temp_Min','Freq_Shake_GT4','Max_Shake','Inspection_Date']  #file

In [8]:
len(Final_Column_Name)

36

In [9]:
#creating a dictionary to rename the column names of each dataframe
rename_cols = { } #file
for idx in range(len(Initial_Col_Name_list)):
  rename_cols[Initial_Col_Name_list[idx]] = Final_Column_Name[idx]


In [10]:
rename_cols

{'ADT_0': 'ADT',
 'AWND': 'Avg_Wind_Speed',
 'DATE_': 'Inspection_Date',
 'DECK_C': 'Deck_Condition',
 'DECK_P': 'Deck_Protection',
 'DECK_S': 'Deck_Design_Type',
 'DECK_W': 'Deck_Width',
 'DEGRE': 'Skew',
 'DT00': 'Days_MinLT_0F',
 'DX32': 'Days_MinLT_32F',
 'DX70': 'Days_MaxGT_70F',
 'DX90': 'Days_MaxGT_90F',
 'FREQUENCY_': 'Freq_Shake_GT4',
 'Frequency_': 'Freq_Shake_GT4',
 'MAIN_': 'Number_Spans',
 'MAX_QUAKE': 'Max_Shake',
 'MAX_S': 'Length_Max_Span',
 'Max_Quake': 'Max_Shake',
 'PERCE': 'ADTT',
 'PRECIPITAT': 'Precipitation',
 'STATE': 'State_Code',
 'STRUCTURE_': 'Structure_Number',
 'STRUCTUR_2': 'Main_Design_Type',
 'STRUCTUR_4': 'Deck_Length',
 'SUBST': 'Substructure_Condition',
 'SUPER': 'Superstructure_Condition',
 'SURFA': 'Wearing_Surface',
 'Shape *': 'Shape *',
 'TEMP_MAX': 'Temp_Max',
 'TEMP_MEAN': 'Temp_Mean',
 'TEMP_MIN': 'Temp_Min',
 'WSF5': 'Peak_Wind_Speed',
 'YEAR_B': 'Year_Built',
 'YEAR_R': 'Reconstructed_Year',
 'lattd': 'Latitude',
 'lngtd': 'Longitude'}

In [23]:
# ConterminousUS.head()

In [11]:
#Rename the columns of each dataframe 
for dataframe in data_frames_list:
  dataframe.rename(columns=rename_cols, inplace=True)

In [12]:
#get all the columns names from all dataframes to check if they are correctly renamed
column_list = []
for frame in data_frames_list:
  column_list.append(frame.columns)

In [26]:
# type(column_list)

In [13]:
#check if all dataframes have same column names as taken from the table final column name after renaming
for j in range(len(column_list)-1):
  if column_list[j].all() != column_list[j+1].all():
    print("All the renamed columns are not same")
    attribute_check = "All the renamed columns are not same"
  else: 
    print("All the renamed columns are same")
    attribute_check = "All the renamed columns are same"


All the renamed columns are same
All the renamed columns are same
All the renamed columns are same
All the renamed columns are same
All the renamed columns are same
All the renamed columns are same
All the renamed columns are same
All the renamed columns are same
All the renamed columns are same
All the renamed columns are same
All the renamed columns are same
All the renamed columns are same
All the renamed columns are same
All the renamed columns are same
All the renamed columns are same
All the renamed columns are same
All the renamed columns are same
All the renamed columns are same
All the renamed columns are same
All the renamed columns are same
All the renamed columns are same
All the renamed columns are same
All the renamed columns are same
All the renamed columns are same
All the renamed columns are same
All the renamed columns are same
All the renamed columns are same
All the renamed columns are same
All the renamed columns are same
All the renamed columns are same
All the re

In [14]:
#concatenate all the dataframes into single dataframe
ConterminousUS = pd.concat(data_frames_list)

In [15]:
ConterminousUS_length = len(ConterminousUS) #file

In [16]:
ConterminousUS_length

612388

In [31]:
#ConterminousUS.rename(columns=rename_cols, inplace=True)

In [32]:
ConterminousUS.head()

State_Code Structure_Number  ...                              geometry  MAX_Quake
0         01  00000000000S702  ...  POINT Z (-87.57041 31.10304 0.00000)        NaN
1         01  00000000000S703  ...  POINT Z (-87.56914 31.10561 0.00000)        NaN
2         01           000071  ...  POINT Z (-85.98808 31.14473 0.00000)        NaN
3         01           000175  ...  POINT Z (-86.05312 31.48880 0.00000)        NaN
4         01           000207  ...  POINT Z (-85.39324 31.22242 0.00000)        NaN

[5 rows x 139 columns]

In [33]:
# all_cols = ConterminousUS.columns
# column_list_total = []
# for frame in all_cols:
#   column_list_total.append(frame.columns)

# for j in range(len(all_cols)-1):
#   if column_list_total[j].all() != column_list_total[j+1].all():
#     print("Not equal")


In [17]:
all_cols = ConterminousUS.columns

In [18]:
len(ConterminousUS.columns)

139

In [19]:
attributes = []
for att in all_cols:
  if att not in Final_Column_Name:
    del ConterminousUS[att]
    #print("not same")
  else:
    #print("same")
    attributes.append(att)

print(ConterminousUS.shape)
#attributes to the file

(612388, 33)


In [20]:
ConterminousUS.columns

Index(['State_Code', 'Structure_Number', 'Year_Built', 'ADT', 'Skew',
       'Main_Design_Type', 'Number_Spans', 'Length_Max_Span', 'Deck_Length',
       'Deck_Width', 'Deck_Condition', 'Superstructure_Condition',
       'Substructure_Condition', 'Inspection_Date', 'Reconstructed_Year',
       'Deck_Design_Type', 'Wearing_Surface', 'Deck_Protection', 'ADTT',
       'Latitude', 'Longitude', 'Freq_Shake_GT4', 'Max_Shake', 'Days_MinLT_0F',
       'Days_MinLT_32F', 'Days_MaxGT_70F', 'Days_MaxGT_90F', 'Avg_Wind_Speed',
       'Peak_Wind_Speed', 'Precipitation', 'Temp_Max', 'Temp_Mean',
       'Temp_Min'],
      dtype='object')

In [21]:
# to check if all the renamed columns are from Final column name

concat_col = ConterminousUS.columns

for cols in concat_col:
  if cols not in Final_Column_Name:
    print("Not existing", cols)

In [22]:
statistics = ConterminousUS.describe() #file

In [23]:
statistics

Year_Built            ADT  ...      Temp_Mean       Temp_Min
count  612388.000000  612388.000000  ...  612388.000000  612388.000000
mean     1975.126557    7825.235411  ...      56.905952      46.243547
std        26.143444   21105.676986  ...       7.875541       8.020886
min      1697.000000       0.000000  ...      29.282200      16.279700
25%      1959.000000     120.000000  ...      51.424000      41.011150
50%      1976.000000     904.000000  ...      55.820500      45.495000
75%      1996.000000    6191.000000  ...      62.667500      51.629700
max      2021.000000  919000.000000  ...      80.811100      76.035700

[8 rows x 25 columns]

In [24]:
Null_exist = ConterminousUS.isnull()

In [25]:
if Null_exist.any == 'True':
  Null_exist = "Null exist"
  print("True")
else : 
  Null_exist = "Null does not exist"
  print("Null does not exist") #file

Null does not exist


In [26]:
with open(r'/content/drive/My Drive/Bridge_Project/Results/Result.txt', 'a') as writefile:
        writefile.write("\n")
        writefile.write(" Bridge Project Results ")
        writefile.write("\n")
        writefile.write(" state_name_dict_cols ")
        writefile.write("\n")
        writefile.write(str(state_name_dict_cols))
        writefile.write("\n")
        writefile.write(" data_frames_rows_list = ")
        writefile.write(str(data_frames_rows_list))
        writefile.write("\n")
        writefile.write("\n")
        writefile.write(" data_frames_cols_list ")
        writefile.write(str(data_frames_cols_list))
        writefile.write("\n")
        writefile.write("\n")
        writefile.write(" check_cols_same")
        writefile.write(check_cols_same)
        writefile.write("\n")
        writefile.write("\n")
        writefile.write(" check_tot_rows  ")
        writefile.write("\n")
        writefile.write("\n")
        writefile.write(check_tot_rows)
        writefile.write("\n")
        writefile.write("\n")
        writefile.write(" Initial_Col_Name_list = ")
        writefile.write("\n")
        writefile.write(str(Initial_Col_Name_list))
        writefile.write("\n")
        writefile.write(" Final_Column_Name = ")
        writefile.write("\n")
        writefile.write(str(Final_Column_Name))
        writefile.write("\n")
        writefile.write("\n")
        writefile.write(" rename_cols ")
        writefile.write(str(rename_cols))
        writefile.write("\n")
        writefile.write(" attribute_check")
        writefile.write(str(attribute_check))
        writefile.write("\n")
        writefile.write(" ConterminousUS_length = ")
        writefile.write("\n")
        writefile.write(str(ConterminousUS_length))
        writefile.write("\n")
        writefile.write(" statistics = ")
        writefile.write("\n")
        writefile.write(str(statistics))
        writefile.write("\n")
        writefile.write(" Null_exist = ")
        writefile.write("\n")
        writefile.write(Null_exist)
        writefile.write("\n")

In [27]:
shape_files_names_list = []
for i in shape_files:
  shape_files_names_list.append(i.split('.')[0]) 


In [28]:
len(shape_files_names_list)

49

In [46]:
# state_code_key = list(range(1,57))
# len(state_code_key)

In [47]:
# keys_deleted = [2,3,7,14,15,43,52]
# len(keys_deleted)

In [48]:
# for item in keys_deleted:
#   state_code_key.remove(item)

# len(state_code_key)

In [29]:
state_code_key = np.unique(ConterminousUS['State_Code'].to_list())


In [30]:
state_code_key_conv = []
for i in range(0,len(state_code_key)):
  print(i)
  if i < 6:
    state_code_key_conv.append(state_code_key[i])
  else:
    
    state_code_key_conv.append(float(state_code_key[i]))
  


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48


In [31]:
state_code_value = shape_files_names_list

In [32]:
State_code_dict = { }
for code in range(len(state_code_key)):
  State_code_dict[(state_code_key_conv[code])] = state_code_value[code]

In [33]:
State_code_dict

{'01': 'Alabama',
 '04': 'Arizona',
 '05': 'Arkansas',
 '06': 'California',
 '08': 'Colorado',
 '09': 'Connecticut',
 10.0: 'Delaware',
 11.0: 'District_of_Columbia',
 12.0: 'Florida',
 13.0: 'Georgia',
 16.0: 'Idaho',
 17.0: 'Illinois',
 18.0: 'Indiana',
 19.0: 'Iowa',
 20.0: 'Kansas',
 21.0: 'Kentucky',
 22.0: 'Louisiana',
 23.0: 'Maine',
 24.0: 'Maryland',
 25.0: 'Massachusetts',
 26.0: 'Michigan',
 27.0: 'Minnesota',
 28.0: 'Mississippi',
 29.0: 'Missouri',
 30.0: 'Montana',
 31.0: 'Nebraska',
 32.0: 'Nevada',
 33.0: 'New_Hampshire',
 34.0: 'New_Jersey',
 35.0: 'New_Mexico',
 36.0: 'New_York',
 37.0: 'North_Carolina',
 38.0: 'North_Dakota',
 39.0: 'Ohio',
 40.0: 'Oklahoma',
 41.0: 'Oregon',
 42.0: 'Pennsylvania',
 44.0: 'Rhode_Island',
 45.0: 'South_Carolina',
 46.0: 'South_Dakota',
 47.0: 'Tennessee',
 48.0: 'Texas',
 49.0: 'Utah',
 50.0: 'Vermont',
 51.0: 'Virginia',
 53.0: 'Washington',
 54.0: 'West_Virginia',
 55.0: 'Wisconsin',
 56.0: 'Wyoming'}

In [34]:
#create a new column State by replacing the numbers with their respective state names
ConterminousUS['State'] = ConterminousUS['State_Code']
ConterminousUS['State'].replace(State_code_dict, inplace=True)

In [55]:
ConterminousUS.head()

State_Code Structure_Number  Year_Built  ...  Temp_Mean  Temp_Min    State
0         01  00000000000S702      1999.0  ...    69.1455   59.1323  Alabama
1         01  00000000000S703      2002.0  ...    69.3045   59.2592  Alabama
2         01           000071      1913.0  ...    67.8229   56.7833  Alabama
3         01           000175      1921.0  ...    67.7732   56.5875  Alabama
4         01           000207      1923.0  ...    68.4901   58.1810  Alabama

[5 rows x 33 columns]

In [35]:
list2 = ConterminousUS['State_Code'].to_list()
len(np.unique(list2))

49

In [36]:
np.unique(list2)

array(['01', '04', '05', '06', '08', '09', '10.0', '11.0', '12.0', '13.0',
       '16.0', '17.0', '18.0', '19.0', '20.0', '21.0', '22.0', '23.0',
       '24.0', '25.0', '26.0', '27.0', '28.0', '29.0', '30.0', '31.0',
       '32.0', '33.0', '34.0', '35.0', '36.0', '37.0', '38.0', '39.0',
       '40.0', '41.0', '42.0', '44.0', '45.0', '46.0', '47.0', '48.0',
       '49.0', '50.0', '51.0', '53.0', '54.0', '55.0', '56.0'],
      dtype='<U4')

In [37]:
list3 = ConterminousUS['State'].to_list()
np.unique(list3)

array(['Alabama', 'Arizona', 'Arkansas', 'California', 'Colorado',
       'Connecticut', 'Delaware', 'District_of_Columbia', 'Florida',
       'Georgia', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas',
       'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts',
       'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana',
       'Nebraska', 'Nevada', 'New_Hampshire', 'New_Jersey', 'New_Mexico',
       'New_York', 'North_Carolina', 'North_Dakota', 'Ohio', 'Oklahoma',
       'Oregon', 'Pennsylvania', 'Rhode_Island', 'South_Carolina',
       'South_Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont',
       'Virginia', 'Washington', 'West_Virginia', 'Wisconsin', 'Wyoming'],
      dtype='<U20')

In [38]:
#check if the datatype is consistent after changing the state name.
type(ConterminousUS['State'].values[0])

str

In [39]:
ConterminousUS.columns

Index(['State_Code', 'Structure_Number', 'Year_Built', 'ADT', 'Skew',
       'Main_Design_Type', 'Number_Spans', 'Length_Max_Span', 'Deck_Length',
       'Deck_Width', 'Deck_Condition', 'Superstructure_Condition',
       'Substructure_Condition', 'Inspection_Date', 'Reconstructed_Year',
       'Deck_Design_Type', 'Wearing_Surface', 'Deck_Protection', 'ADTT',
       'Latitude', 'Longitude', 'Freq_Shake_GT4', 'Max_Shake', 'Days_MinLT_0F',
       'Days_MinLT_32F', 'Days_MaxGT_70F', 'Days_MaxGT_90F', 'Avg_Wind_Speed',
       'Peak_Wind_Speed', 'Precipitation', 'Temp_Max', 'Temp_Mean', 'Temp_Min',
       'State'],
      dtype='object')

In [40]:
#range of the years 
year_range = np.unique(ConterminousUS['Year_Built'].values)
year_range.sort

<function ndarray.sort>

In [41]:
type(year_range)

numpy.ndarray

In [42]:
year_range

array([1697., 1764., 1765., 1777., 1789., 1792., 1796., 1798., 1800.,
       1801., 1804., 1807., 1809., 1810., 1812., 1817., 1820., 1822.,
       1823., 1824., 1825., 1826., 1827., 1828., 1829., 1830., 1831.,
       1832., 1833., 1834., 1835., 1836., 1837., 1838., 1839., 1840.,
       1841., 1842., 1844., 1845., 1846., 1847., 1848., 1849., 1850.,
       1851., 1852., 1853., 1854., 1855., 1856., 1857., 1858., 1859.,
       1860., 1861., 1862., 1863., 1864., 1865., 1866., 1867., 1868.,
       1869., 1870., 1871., 1872., 1873., 1874., 1875., 1876., 1877.,
       1878., 1879., 1880., 1881., 1882., 1883., 1884., 1885., 1886.,
       1887., 1888., 1889., 1890., 1891., 1892., 1893., 1894., 1895.,
       1896., 1897., 1898., 1899., 1900., 1901., 1902., 1903., 1904.,
       1905., 1906., 1907., 1908., 1909., 1910., 1911., 1912., 1913.,
       1914., 1915., 1916., 1917., 1918., 1919., 1920., 1921., 1922.,
       1923., 1924., 1925., 1926., 1927., 1928., 1929., 1930., 1931.,
       1932., 1933.,

In [44]:
Inspection_range = np.unique(ConterminousUS['Inspection_Date'].values)
Inspection_range

array([ 100.,  101.,  105.,  108.,  109.,  110.,  111.,  112.,  113.,
        115.,  116.,  117.,  118.,  119.,  120.,  197.,  199.,  203.,
        207.,  210.,  215.,  216.,  217.,  218.,  219.,  220.,  292.,
        295.,  299.,  303.,  304.,  305.,  307.,  308.,  309.,  310.,
        312.,  313.,  314.,  315.,  316.,  317.,  318.,  319.,  320.,
        406.,  408.,  410.,  411.,  412.,  413.,  414.,  415.,  416.,
        417.,  418.,  419.,  420.,  430.,  493.,  504.,  507.,  509.,
        511.,  513.,  514.,  515.,  516.,  517.,  518.,  519.,  520.,
        593.,  606.,  607.,  608.,  611.,  614.,  615.,  616.,  617.,
        618.,  619.,  620.,  695.,  701.,  707.,  708.,  709.,  710.,
        711.,  712.,  714.,  715.,  716.,  717.,  718.,  719.,  720.,
        794.,  798.,  805.,  806.,  808.,  809.,  810.,  811.,  812.,
        813.,  814.,  815.,  816.,  817.,  818.,  819.,  820.,  824.,
        898.,  900.,  905.,  906.,  909.,  910.,  911.,  912.,  913.,
        914.,  915.,

In [45]:
digit = []
for num in Inspection_range:
  #print(num)
  #print(type(num))
  digit.append(int(str(int(num))[-2:]))

In [46]:
#unique last 2 digits of the Inpection Year
np.unique(digit)

array([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 24, 30, 88, 92, 93, 94, 95, 97, 98, 99])

In [47]:
year_list = []
for i in digit:
  if i < 10:
    year_list.append(int('20' + '0' + str(i)))
  elif i < 21:
    year_list.append(int('20' + str(i)))
  else:
    year_list.append(int('19' + str(i)))



In [50]:
year_dict = { } 
for year in range(len(year_range)):
  year_dict[year_range[year]] = year_list[year]


IndexError: ignored

In [ ]:
year_dict

In [70]:
ConterminousUS['Inspection_Year'] = ConterminousUS['Year_Built']
ConterminousUS['Inspection_Year'].replace(year_dict, inplace=True)

In [71]:
np.unique(ConterminousUS['Inspection_Year'].values)

array([1921., 1922., 1923., 1924., 1925., 1926., 1927., 1928., 1929.,
       1930., 1931., 1932., 1933., 1934., 1935., 1936., 1937., 1938.,
       1939., 1940., 1941., 1942., 1943., 1944., 1945., 1946., 1947.,
       1948., 1949., 1950., 1951., 1952., 1953., 1954., 1955., 1956.,
       1957., 1958., 1959., 1960., 1961., 1962., 1963., 1964., 1965.,
       1966., 1967., 1968., 1969., 1970., 1971., 1972., 1973., 1974.,
       1975., 1976., 1977., 1978., 1979., 1980., 1981., 1982., 1983.,
       1984., 1985., 1986., 1987., 1988., 1989., 1990., 1991., 1992.,
       1993., 1994., 1995., 1996., 1997., 1998., 1999., 2000., 2001.,
       2002., 2003., 2004., 2005., 2006., 2007., 2008., 2009., 2010.,
       2011., 2012., 2013., 2014., 2015., 2016., 2017., 2018., 2019.,
       2020.])

In [72]:
type(np.unique(ConterminousUS['Inspection_Year'].values)[0])

numpy.float64

In [73]:

# ConterminousUS['Inspection_Year'] = ConterminousUS['Year_Built']
# for num in ConterminousUS['Year_Built']:
#   digits = int(str(int(num))[-2:])
#   print(digits)
#   if digits < 10:
#     ConterminousUS['Inspection_Year'].replace((int('20' + '0' + str(digits))), inplace=True)
#   elif digits < 21:
#     ConterminousUS['Inspection_Year'].replace((int('20' + str(digits))), inplace=True)
#   else:
#     ConterminousUS['Inspection_Year'].replace((int('19' + str(digits))), inplace=True)
  

In [74]:
ConterminousUS.columns

Index(['State_Code', 'Structure_Number', 'Year_Built', 'ADT', 'Skew',
       'Main_Design_Type', 'Number_Spans', 'Length_Max_Span', 'Deck_Length',
       'Deck_Width', 'Deck_Condition', 'Superstructure_Condition',
       'Substructure_Condition', 'Reconstructed_Year', 'Deck_Design_Type',
       'Wearing_Surface', 'Deck_Protection', 'ADTT', 'Latitude', 'Longitude',
       'Freq_Shake_GT4', 'Max_Shake', 'Days_MinLT_0F', 'Days_MinLT_32F',
       'Days_MaxGT_70F', 'Days_MaxGT_90F', 'Avg_Wind_Speed', 'Peak_Wind_Speed',
       'Precipitation', 'Temp_Max', 'Temp_Mean', 'Temp_Min', 'State',
       'Inspection_Year'],
      dtype='object')

In [ ]:
np.unique(ConterminousUS['Reconstructed_Year'].values)

In [ ]:
# ConterminousUS['Reconstructed'] = ConterminousUS['Reconstructed_Year']

# for entry in ConterminousUS['Reconstructed']:
#   #print(type(entry))
#   if entry == 0:
#     ConterminousUS['Reconstructed'] = 0
#   else:
#     ConterminousUS['Reconstructed'] = 1

In [93]:
ConterminousUS['Reconstructed'] = ConterminousUS['Reconstructed_Year']

In [94]:
reconstructed_values_list = ConterminousUS['Reconstructed'].values

In [ ]:
np.unique(reconstructed_values_list)

In [96]:
for i in range(0,len(reconstructed_values_list)):
  if reconstructed_values_list[i] == 0:
    reconstructed_values_list[i] = 0
  else:
    reconstructed_values_list[i] = 1

In [97]:
np.unique(reconstructed_values_list)

array([0., 1.])

In [98]:
ConterminousUS['Reconstructed'] = reconstructed_values_list

In [ ]:
ConterminousUS[['Reconstructed_Year','Reconstructed']][10000:10020]

In [106]:
#check the datatype of the reconstructed column entries
type(ConterminousUS['Reconstructed'].values[0])

numpy.float64

In [107]:
Age_list = [] 
Inspection_list = []
Year_Built_list = []
Reconstructed_list = []

Inspection_list = (ConterminousUS['Inspection_Year'].values)
Year_Built_list = (ConterminousUS['Year_Built'].values)
Reconstructed_list = (ConterminousUS['Reconstructed'].values)
Reconstructed_Year_list = (ConterminousUS['Reconstructed_Year'].values)

In [108]:
for index in range(0,len(Reconstructed_list)):
  if Reconstructed_list[index] == 0:
    Age_list.append(Inspection_list[index] - Year_Built_list[index])
  else:
    Age_list.append(Inspection_list[index] - Reconstructed_Year_list[index])

In [109]:
len(Age_list)

612388

In [110]:
type(Age_list[0])

numpy.float64

In [112]:
print(np.unique(Age_list))

[-1.250e+02 -1.060e+02 -1.000e+02 -9.700e+01 -9.600e+01 -9.500e+01
 -9.400e+01 -9.300e+01 -9.200e+01 -9.100e+01 -9.000e+01 -8.900e+01
 -8.800e+01 -8.700e+01 -8.600e+01 -8.500e+01 -8.400e+01 -8.300e+01
 -8.200e+01 -8.100e+01 -8.000e+01 -7.900e+01 -7.800e+01 -7.700e+01
 -7.600e+01 -7.500e+01 -7.400e+01 -7.300e+01 -7.200e+01 -7.100e+01
 -7.000e+01 -6.900e+01 -6.800e+01 -6.700e+01 -6.600e+01 -6.500e+01
 -6.400e+01 -6.300e+01 -6.200e+01 -6.100e+01 -6.000e+01 -5.900e+01
 -5.800e+01 -5.700e+01 -5.600e+01 -5.500e+01 -5.400e+01 -5.300e+01
 -5.200e+01 -5.100e+01 -5.000e+01 -4.900e+01 -4.800e+01 -4.700e+01
 -4.600e+01 -4.500e+01 -4.400e+01 -4.300e+01 -4.200e+01 -4.100e+01
 -4.000e+01 -3.900e+01 -3.800e+01 -3.700e+01 -3.600e+01 -3.500e+01
 -3.400e+01 -3.300e+01 -3.200e+01 -3.100e+01 -3.000e+01 -2.900e+01
 -2.800e+01 -2.700e+01 -2.600e+01 -2.500e+01 -2.400e+01 -2.300e+01
 -2.200e+01 -2.100e+01 -2.000e+01 -1.900e+01 -1.800e+01 -1.700e+01
 -1.600e+01 -1.500e+01 -1.400e+01 -1.300e+01 -1.200e+01 -1.100

In [113]:
ConterminousUS.head()

State_Code Structure_Number  ...  Inspection_Year  Reconstructed
0         01  00000000000S702  ...           1999.0            0.0
1         01  00000000000S703  ...           2002.0            0.0
2         01           000071  ...           2013.0            1.0
3         01           000175  ...           1921.0            1.0
4         01           000207  ...           1923.0            0.0

[5 rows x 35 columns]

In [114]:
ConterminousUS['Inspection_Date']

KeyError: ignored